create table "public"."matches" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."matches" enable row level security;

create table "public"."stats" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "wins" bigint not null default '0'::bigint,
    "best_wpm" real not null default '0'::real
);


alter table "public"."stats" enable row level security;

create table "public"."user_matches" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "match_id" uuid
);


alter table "public"."user_matches" enable row level security;

CREATE UNIQUE INDEX matches_pkey ON public.matches USING btree (id);

CREATE UNIQUE INDEX stats_pkey ON public.stats USING btree (id);

CREATE UNIQUE INDEX user_matches_pkey ON public.user_matches USING btree (id);

alter table "public"."matches" add constraint "matches_pkey" PRIMARY KEY using index "matches_pkey";

alter table "public"."stats" add constraint "stats_pkey" PRIMARY KEY using index "stats_pkey";

alter table "public"."user_matches" add constraint "user_matches_pkey" PRIMARY KEY using index "user_matches_pkey";

alter table "public"."stats" add constraint "public_stats_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."stats" validate constraint "public_stats_id_fkey";

alter table "public"."user_matches" add constraint "public_user_matches_match_id_fkey" FOREIGN KEY (match_id) REFERENCES matches(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_matches" validate constraint "public_user_matches_match_id_fkey";

alter table "public"."user_matches" add constraint "public_user_matches_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_matches" validate constraint "public_user_matches_user_id_fkey";

grant delete on table "public"."matches" to "anon";

grant insert on table "public"."matches" to "anon";

grant references on table "public"."matches" to "anon";

grant select on table "public"."matches" to "anon";

grant trigger on table "public"."matches" to "anon";

grant truncate on table "public"."matches" to "anon";

grant update on table "public"."matches" to "anon";

grant delete on table "public"."matches" to "authenticated";

grant insert on table "public"."matches" to "authenticated";

grant references on table "public"."matches" to "authenticated";

grant select on table "public"."matches" to "authenticated";

grant trigger on table "public"."matches" to "authenticated";

grant truncate on table "public"."matches" to "authenticated";

grant update on table "public"."matches" to "authenticated";

grant delete on table "public"."matches" to "service_role";

grant insert on table "public"."matches" to "service_role";

grant references on table "public"."matches" to "service_role";

grant select on table "public"."matches" to "service_role";

grant trigger on table "public"."matches" to "service_role";

grant truncate on table "public"."matches" to "service_role";

grant update on table "public"."matches" to "service_role";

grant delete on table "public"."stats" to "anon";

grant insert on table "public"."stats" to "anon";

grant references on table "public"."stats" to "anon";

grant select on table "public"."stats" to "anon";

grant trigger on table "public"."stats" to "anon";

grant truncate on table "public"."stats" to "anon";

grant update on table "public"."stats" to "anon";

grant delete on table "public"."stats" to "authenticated";

grant insert on table "public"."stats" to "authenticated";

grant references on table "public"."stats" to "authenticated";

grant select on table "public"."stats" to "authenticated";

grant trigger on table "public"."stats" to "authenticated";

grant truncate on table "public"."stats" to "authenticated";

grant update on table "public"."stats" to "authenticated";

grant delete on table "public"."stats" to "service_role";

grant insert on table "public"."stats" to "service_role";

grant references on table "public"."stats" to "service_role";

grant select on table "public"."stats" to "service_role";

grant trigger on table "public"."stats" to "service_role";

grant truncate on table "public"."stats" to "service_role";

grant update on table "public"."stats" to "service_role";

grant delete on table "public"."user_matches" to "anon";

grant insert on table "public"."user_matches" to "anon";

grant references on table "public"."user_matches" to "anon";

grant select on table "public"."user_matches" to "anon";

grant trigger on table "public"."user_matches" to "anon";

grant truncate on table "public"."user_matches" to "anon";

grant update on table "public"."user_matches" to "anon";

grant delete on table "public"."user_matches" to "authenticated";

grant insert on table "public"."user_matches" to "authenticated";

grant references on table "public"."user_matches" to "authenticated";

grant select on table "public"."user_matches" to "authenticated";

grant trigger on table "public"."user_matches" to "authenticated";

grant truncate on table "public"."user_matches" to "authenticated";

grant update on table "public"."user_matches" to "authenticated";

grant delete on table "public"."user_matches" to "service_role";

grant insert on table "public"."user_matches" to "service_role";

grant references on table "public"."user_matches" to "service_role";

grant select on table "public"."user_matches" to "service_role";

grant trigger on table "public"."user_matches" to "service_role";

grant truncate on table "public"."user_matches" to "service_role";

grant update on table "public"."user_matches" to "service_role";


